{
 "title": "URL Shortener Dashboard",
 "tags": [
  "URL Shortener",
  "API",
  "Metrics"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Top 10 URLs mais acessadas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "topk(10, url_hits_total)", "legendFormat": "{{shortKey}}" }
   ]
  },
  {
   "title": "Hits por URL ao longo do tempo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "rate(url_hits_total[5m])", "legendFormat": "{{shortKey}}" }
   ]
  },
  {
   "title": "Latência da API (média e p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, endpoint))",
     "legendFormat": "P95 Latency"
    }
   ]
  }
 ]
}